name: Tests

on:
  push:
    branches: [main]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
      - name: Compile project
        run: |
          chmod +x gradlew
          ./gradlew jar
      - name: Run checks
        run: |
          ./gradlew check
      - uses: codecov/codecov-action@v2
      - name: Publish snapshot
        if: "github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')"
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          GITLAB_DEPLOY_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}
      - run: rm -rf /tmp/publish-site-to-gitlab
      - name: Publish dev website
        if: "github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')"
        run: ci/publish-dev-site-to-gitlab.sh
        env:
          GITLAB_SITE_PUSH_TOKEN: ${{ secrets.GITLAB_SITE_PUSH_TOKEN }}
      
      # NOTE: added for the deprecation announcement things
      - name: Publish production website
        run: ci/publish-prod-site-to-gitlab.sh
        env:
          GITLAB_SITE_PUSH_TOKEN: ${{ secrets.GITLAB_SITE_PUSH_TOKEN }}

  publish:
    if: "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-20.04
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew build
      - name: Publish non-snapshot version
        run: ./gradlew publish -PallowNonSnapshotRelease
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          GITLAB_DEPLOY_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}
      - name: Publish production website
        run: ci/publish-prod-site-to-gitlab.sh
        env:
          GITLAB_SITE_PUSH_TOKEN: ${{ secrets.GITLAB_SITE_PUSH_TOKEN }}
